apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi