apiVersion: v1
kind: Service
metadata:
  name: svc-minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  loadBalancerIP: 40.117.82.25
  ports:
  - port: 25565
    name: server
  - port: 25575
    name: admin
  selector:
    app: minecraft
status:
  loadBalancer:
    ingress:
    - ip: 40.117.82.25